import test from 'node:test';import assert from 'node:assert/strict';import {validateRequest,adminAllowed,checkOrigin} from '../lib/services.js';import {basicAnswer} from '../lib/knowledge.js';import {calendarDraft,localToUTC} from '../lib/calendar.js';import chat from '../api/concierge.js';import requests from '../api/requests.js';import admin from '../api/admin.js';
const sample={id:'a2b3c4d5-6789-1234-5678-abcd12345678',name:'Guest',email:'guest@example.com',kind:'Menu planning',date:'2027-01-20',time:'15:00',timezone:'America/New_York',consent:true,reminders:true};const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v},status(s){this.code=s;return this},json(d){this.data=d;return this}});
test('intake requires consent and validates calendar dates, times and timezone',()=>{assert.equal(validateRequest(sample).status,'requested');for(const change of [{consent:false},{email:'bad'},{date:'2027-02-31'},{time:'25:00'},{timezone:'bad/time'},{eventDate:'2027-13-01'},{date:'',time:'15:00'}])assert.throws(()=>validateRequest({...sample,...change}));});
test('calendar draft is explicitly tentative and contains no client contact or dietary details',()=>{const s=calendarDraft({...sample,preferences:'Sensitive',phone:'PRIVATE'});assert.match(s,/STATUS:TENTATIVE/);assert.match(s,/REQUESTED/);assert.match(s,/DTSTART:20270120T200000Z/);assert.match(s,/DTEND:20270120T202000Z/);assert.doesNotMatch(s,/guest@example|Sensitive|PRIVATE/);assert.throws(()=>calendarDraft({...sample,time:''}));});
test('basic guide does not invent prices or reservations',()=>{assert.match(basicAnswer('price'),/quoted individually/);assert.match(basicAnswer('book'),/does not reserve/);assert.match(basicAnswer('allergy'),/cannot guarantee/);});
test('owner API rejects unauthenticated requests',async()=>{const r=response();await admin({method:'GET',headers:{}},r);assert.equal(r.code,401);assert.equal(adminAllowed({headers:{authorization:'Bearer short'}}),false)});
test('intake without storage never claims saved or submits elsewhere',async()=>{const r=response();await requests({method:'POST',headers:{},body:sample},r);assert.equal(r.code,503);assert.equal(r.data.fallback,true);assert.equal(r.data.saved,undefined)});
test('chat validates conversation and rejects foreign origins',async()=>{let r=response();await chat({method:'POST',headers:{},body:{messages:[]}},r);assert.equal(r.code,400);r=response();await chat({method:'POST',headers:{origin:'https://evil.example'},body:{messages:[{role:'user',content:'hi'}]}},r);assert.equal(r.code,403);assert.equal(checkOrigin({headers:{origin:'https://www.lasobremesa.vip'}}),true)});
test('chat has a verified fallback with no AI credential',async()=>{delete process.env.VERCEL_OIDC_TOKEN;delete process.env.AI_GATEWAY_API_KEY;const r=response();await chat({method:'POST',headers:{},body:{messages:[{role:'user',content:'What does a dinner cost?'}]}},r);assert.equal(r.code,200);assert.equal(r.data.mode,'guide');assert.match(r.data.reply,/quoted individually/)});

test('calendar draft converts timezone and rejects nonexistent DST time',()=>{assert.equal(localToUTC('2027-07-20','15:00','America/New_York'),'2027-07-20T19:00:00.000Z');assert.equal(localToUTC('2027-01-20','00:00','America/New_York'),'2027-01-20T05:00:00.000Z');assert.throws(()=>localToUTC('2027-03-14','02:30','America/New_York'));assert.match(basicAnswer('Pricing'),/quoted individually/)});
test('private request storage saves once and duplicate retries do not send again',async()=>{const oldFetch=globalThis.fetch;const keys=['UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN'];const before=keys.map(k=>process.env[k]);process.env[keys[0]]='https://storage.example';process.env[keys[1]]='test';const rows=new Map();let created=0;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://storage.example');const [cmd,key,...args]=JSON.parse(options.body);let result=null;if(cmd==='GET')result=rows.get(key)||null;if(cmd==='SET'){if(args.includes('NX')&&rows.has(key))result=null;else{rows.set(key,args[0]);created++;result='OK'}}if(cmd==='INCR'){result=+(rows.get(key)||0)+1;rows.set(key,result)}if(cmd==='EXPIRE'||cmd==='ZADD')result=1;return {ok:true,json:async()=>({result})}};try{let r=response();await requests({method:'POST',headers:{},body:sample},r);assert.equal(r.code,201);assert.equal(r.data.saved,true);assert.equal(r.data.emailAccepted,false);assert.equal(JSON.parse(rows.get(`sm:request:${sample.id}`)).status,'requested');r=response();await requests({method:'POST',headers:{},body:sample},r);assert.equal(r.code,200);assert.equal(r.data.duplicate,true);assert.equal(created,1)}finally{globalThis.fetch=oldFetch;keys.forEach((k,i)=>{if(before[i]===undefined)delete process.env[k];else process.env[k]=before[i]})}});
