export const KNOWLEDGE = `Sobre Mesa is Chef Adam Bishop's Mexican private dining and culinary events brand in Richmond, Virginia; destination events are considered by inquiry. Private dinners, celebrations, wedding weekends, corporate dinners, al pastor and taco experiences, tequila and mezcal pairings. More than 12 years living in Mexico, including Puerto Vallarta, Mexico City and Jalisco. Confirmed signature dishes: tacos al pastor; huevos estrellados sobre tamal rojo; sopa de tortilla; tacos de short rib; tacos de pato; ceviche; cochinita pibil; pato con mole negro oaxaqueño. Education: Instituto de Gastronomía y Repostería Franco Mexicano, Puerto Vallarta; Diploma de Cuisine y Alta Cocina; additional specialties Cocina Internacional and Diplomado de Cocina Mexicana. English and Spanish. Cuisine: al pastor cooked over fire, handmade tortillas, carnitas, ribeye/Wagyu options, mole, tamales and huevos estrellados, Pacific tuna, grilled octopus, elote, tortas ahogadas, cacao/chocolate/avocado desserts. Sample menus: De la costa a Oaxaca; Masa & fuego; Sabores de México. Dessert and pairings agreed individually. All menus customized. No published fixed prices, minimum guest count, availability, service inclusions, cancellation terms, alcohol licensing or allergen guarantees. Chef confirms these directly. Phone 804-866-7307; chef@lasobremesa.vip. Requests are not bookings. No payments collected by concierge. Brand name is always two words: Sobre Mesa. Refer to the culinary school as Franco Mexicano, never Franco Mexican. Food allergies must be reviewed with chef; never guarantee allergen-free preparation.`;
export function basicAnswer(message) {
 const q=message.toLowerCase().replace(/\bchefy\b/g,'').trim();
 if(/allerg|gluten|vegan|vegetarian|diet/.test(q)) return 'Please tell us about dietary preferences in your request. For allergies, Chef Adam must review the ingredients and preparation directly before agreeing to a menu. We cannot guarantee an allergen-free environment through chat.';
 if(/pric|cost|budget|rate|minimum|deposit|cancel/.test(q)) return 'Each gathering is quoted individually around the menu, guest count, location and service needs. What kind of gathering do you have in mind? Pricing and booking terms are confirmed directly.';
 if(/where|location|travel|virginia|richmond|destination/.test(q)) return 'Sobre Mesa serves the Richmond region in Virginia. Destination events are considered by inquiry. Include your venue or city when planning your gathering.';
 if(/book|appointment|availab|schedule|call|date|time/.test(q)) return 'You can request an introductory call, an event consultation or a menu-planning conversation. Choose “Arrange a call” when you’re ready to share a preferred time. Chef Adam confirms availability; submitting a request does not reserve a time.';
 if(/menu|ceviche|pibil|pato|short rib|soup|mole|taco|pastor|tamale|seafood|octopus|chocolate|dessert|wagyu|ribeye|carnita|tortilla/.test(q)) return 'The kitchen centers on Mexican cooking: al pastor, short-rib and duck tacos, huevos estrellados over tamal rojo, tortilla soup, ceviche, cochinita pibil and duck with Oaxacan mole negro. Three starting points are De la costa a Oaxaca, Masa & fuego, and Sabores de México. Would you like a seafood-focused menu or something centered on slow-cooked meat?';
 if(/mezcal|tequila|agave|alcohol/.test(q)) return 'Tequila and mezcal pairing experiences explore origin, aroma and how each spirit relates to the food. Ask Chef Adam about the format and arrangements for your venue; alcohol service details must be confirmed directly.';
 if(/chef|adam|train|school|credential|experience|spanish/.test(q)) return 'Chef Adam Bishop combines more than twelve years living in Mexico with a culinary degree from Instituto de Gastronomía y Repostería Franco Mexicano in Puerto Vallarta. His culinary degree is Diploma de Cuisine y Alta Cocina, with specialties in Cocina Internacional and Diplomado de Cocina Mexicana. He speaks English and Spanish.';
 if(/anniversary|birthday|graduation|reunion|dinner|gathering/.test(q)) return 'For your gathering, a useful starting point is a seasonal opening bite, a seafood course, mole or a fire-cooked main, and a cacao dessert. Chef Adam adapts the menu to your occasion and dietary preferences. What occasion are you celebrating?';
 if(/wedding|corporate|party|event|service|celebrat|private/.test(q)) return 'Sobre Mesa offers private dining, celebrations and wedding-weekend experiences, corporate dinners, and culinary experiences such as al pastor, tacos and agave pairings. The menu and service are developed around your gathering.';
 if(/contact|email|phone|text/.test(q)) return 'Reach Chef Adam at 804-866-7307 or chef@lasobremesa.vip. You can also prepare a detailed inquiry here for a call, event or menu-planning conversation.';
 if(/^(hi|hello|hey|hola|good morning)[! .]*$/.test(q)) return 'Hola, I’m Chefy, Sobre Mesa’s AI chef concierge. What would you like to know?';
 return 'I can help with Sobre Mesa’s cuisine, experiences, Chef Adam’s background and consultation requests. For a question specific to your event, Chef Adam can answer directly. What would you like to explore: the food or your gathering?';
}
