export const KNOWLEDGE = `Sobre Mesa is Chef Adam Bishop's Mexican private dining and culinary events brand in Richmond, Virginia; destination events are considered by inquiry. Private dinners, celebrations, wedding weekends, corporate dinners, trompo/taco experiences, tequila and mezcal pairings. More than 12 years living in Mexico, including Puerto Vallarta, Mexico City and Jalisco. Education: Instituto de Gastronomía y Repostería Franco-Mexicano, Puerto Vallarta; Diploma de Cuisine y Alta Cocina; additional specialties Cocina Internacional and Diplomado de Cocina Mexicana. English and Spanish. Cuisine: al pastor carved from a trompo, handmade tortillas, carnitas, ribeye/Wagyu options, mole, tamales and huevos estrellados, Pacific tuna, grilled octopus, elote, tortas ahogadas, cacao/chocolate/avocado desserts. Sample tasting menu: seasonal opening bite, tuna, mole, premium fire-cooked protein, cacao dessert. All menus customized. No published fixed prices, minimum guest count, availability, service inclusions, cancellation terms, alcohol licensing or allergen guarantees. Chef confirms these directly. Phone 804-866-7307; chef@lasobremesa.vip. Requests are not bookings. No payments collected by concierge. Food allergies must be reviewed with chef; never guarantee allergen-free preparation.`;
export function basicAnswer(message) {
 const q=message.toLowerCase();
 if(/allerg|gluten|vegan|vegetarian|diet/.test(q)) return 'Please tell us about dietary preferences in your request. For allergies, Chef Adam must review the ingredients and preparation directly before agreeing to a menu. We cannot guarantee an allergen-free environment through chat.';
 if(/price|cost|budget|rate|minimum|deposit|cancel/.test(q)) return 'Each gathering is quoted individually around the menu, guest count, location and service needs. Share your budget range and occasion, and Chef Adam can develop a proposal. Pricing and booking terms are confirmed directly.';
 if(/where|location|travel|virginia|richmond|destination/.test(q)) return 'Sobre Mesa serves the Richmond region in Virginia. Destination events are considered by inquiry. Include your venue or city when planning your gathering.';
 if(/book|appointment|availab|schedule|call|date|time/.test(q)) return 'You can request an introductory call, an event consultation or a menu-planning conversation. Choose “Plan with us” to share your preferred date, time and timezone. Chef Adam confirms availability; submitting a request does not reserve a time.';
 if(/menu|mole|taco|pastor|tamale|seafood|octopus|chocolate|dessert|wagyu|ribeye|carnita|tortilla/.test(q)) return 'The kitchen centers on Mexican cooking: al pastor from the trompo, handmade tortillas, mole, fire-grilled seafood, premium proteins and cacao desserts. Three starting points are Sobre Mesa tasting, Masa & trompo, and Jalisco & agave. Your menu is tailored to the occasion, season and preferences.';
 if(/mezcal|tequila|agave|alcohol/.test(q)) return 'Tequila and mezcal pairing experiences explore origin, aroma and how each spirit relates to the food. Ask Chef Adam about the format and arrangements for your venue; alcohol service details must be confirmed directly.';
 if(/chef|adam|train|school|credential|experience|spanish/.test(q)) return 'Chef Adam Bishop combines more than twelve years living in Mexico with training at Instituto de Gastronomía y Repostería Franco-Mexicano in Puerto Vallarta. His diploma is Diploma de Cuisine y Alta Cocina, with specialties in Cocina Internacional and Diplomado de Cocina Mexicana. He speaks English and Spanish.';
 if(/wedding|corporate|party|event|service|celebrat|private/.test(q)) return 'Sobre Mesa offers private dining, celebrations and wedding-weekend experiences, corporate dinners, and culinary experiences such as trompo, tacos and agave pairings. The menu and service are developed around your gathering.';
 if(/contact|email|phone|text/.test(q)) return 'Reach Chef Adam at 804-866-7307 or chef@lasobremesa.vip. You can also prepare a detailed inquiry here for a call, event or menu-planning conversation.';
 if(/^(hi|hello|hey|hola|good morning)[! .]*$/.test(q)) return 'Welcome to Sobre Mesa. I can help with our cuisine, private dining, event planning and consultation requests. What are you imagining for your gathering?';
 return 'I can help with Sobre Mesa’s cuisine, experiences, Chef Adam’s background and consultation requests. For a question specific to your event, include it in a concierge inquiry so Chef Adam can answer directly.';
}
