import {createHash,timingSafeEqual} from 'node:crypto';
function requiredEnv(key){const value=process.env[key];if(!value)throw new Error('service_not_connected');return value}
export function capabilities(req={headers:{}}){return {storage:!!(process.env.UPSTASH_REDIS_REST_URL&&process.env.UPSTASH_REDIS_REST_TOKEN),email:!!(process.env.RESEND_API_KEY&&process.env.CONCIERGE_OWNER_EMAIL&&process.env.CONCIERGE_FROM_EMAIL),calendar:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.GOOGLE_REFRESH_TOKEN&&process.env.GOOGLE_CALENDAR_ID),ai:!!(process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN||req.headers?.['x-vercel-oidc-token'])}}
export function adminAllowed(req){const expected=process.env.CONCIERGE_ADMIN_TOKEN||'';const actual=String(req.headers.authorization||'').replace(/^Bearer /,'');if(expected.length<32||actual.length!==expected.length)return false;return timingSafeEqual(Buffer.from(actual),Buffer.from(expected))}
export function checkOrigin(req){const o=req.headers.origin;return !o||['https://www.lasobremesa.vip','https://lasobremesa.vip'].includes(o)||o===`https://${process.env.VERCEL_URL}`}
export function json(res,status,data){res.setHeader('Cache-Control','no-store');return res.status(status).json(data)}
export const digest=s=>createHash('sha256').update(s).digest('hex');
export async function redis(command){if(!capabilities().storage)throw new Error('storage_not_connected');const r=await fetch(requiredEnv('UPSTASH_REDIS_REST_URL'),{method:'POST',headers:{Authorization:`Bearer ${process.env.UPSTASH_REDIS_REST_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(8000)});const d=await r.json();if(!r.ok||d.error)throw new Error('storage_request_failed');return d.result}
const memory=new Map();
export async function limited(req,prefix,max,seconds=3600){const ip=String(req.headers['x-forwarded-for']||'anonymous').split(',')[0].trim(),key=`sm:limit:${prefix}:${digest(ip)}:${Math.floor(Date.now()/1000/seconds)}`;if(capabilities().storage){const n=await redis(['INCR',key]);if(n===1)await redis(['EXPIRE',key,seconds]);return n>max}const n=(memory.get(key)||0)+1;memory.set(key,n);if(memory.size>3000)memory.clear();return n>max}
export function validateRequest(b,now=Date.now()) {
 if(!b||typeof b!=='object'||Array.isArray(b))throw new Error('Please complete the request form.');
 if(b.website)throw new Error('Unable to accept this request.');
 const clean=(v,n=300)=>String(v||'').trim().slice(0,n);
 const d={id:clean(b.id,80),name:clean(b.name,120),email:clean(b.email,254).toLowerCase(),phone:clean(b.phone,40),kind:clean(b.kind,40),date:clean(b.date,10),time:clean(b.time,5),timezone:clean(b.timezone,80),eventDate:clean(b.eventDate,10),guests:clean(b.guests,6),location:clean(b.location,200),budget:clean(b.budget,80),preferences:clean(b.preferences,1200),details:clean(b.details,2000),reminders:b.reminders===true,consent:b.consent===true};
 if(!/^[a-z0-9-]{16,80}$/i.test(d.id))throw new Error('Please start a new request.');
 if(!d.name||!/^\S+@\S+\.\S+$/.test(d.email))throw new Error('Please provide your name and a valid email.');
 if(!['Introductory call','Event consultation','Menu planning'].includes(d.kind))throw new Error('Choose a consultation type.');
 if(!d.consent)throw new Error('Please agree to send your request details.');
 if(d.timezone){try{new Intl.DateTimeFormat('en',{timeZone:d.timezone}).format()}catch{throw new Error('Choose a valid timezone.')}}
 const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(new Date(v+'T00:00:00Z').getTime())&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
 if(d.date&&!validDate(d.date))throw new Error('Choose a valid consultation date.');
 if(d.eventDate&&!validDate(d.eventDate))throw new Error('Choose a valid event date.');
 if(d.time&&!d.date)throw new Error('Choose a date for your preferred time.');
 if(!d.timezone)d.timezone='America/New_York';
 if(d.time&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(d.time))throw new Error('Choose a valid consultation time.');
 if(d.date&&d.date<new Date(now).toLocaleDateString('en-CA',{timeZone:'America/New_York'}))throw new Error('Please choose a future consultation date.');
 if(d.guests&&(!/^\d+$/.test(d.guests)||+d.guests<1||+d.guests>10000))throw new Error('Please check the guest count.');
 return {...d,status:'requested',createdAt:new Date(now).toISOString(),notificationWarning:false,notifications:/** @type {Record<string,string>} */ ({})};
}
/** @param {{to:string|undefined,subject:string,text:string,id:string,scheduled_at?:string}} options */
export async function sendMail({to,subject,text,id,scheduled_at=undefined}) {if(!capabilities().email||!to)throw new Error('email_not_connected');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':id},body:JSON.stringify({from:process.env.CONCIERGE_FROM_EMAIL,to:[to],reply_to:'chef@lasobremesa.vip',subject,text,...(scheduled_at?{scheduled_at}:{})}),signal:AbortSignal.timeout(8000)});const d=await r.json();if(!r.ok||!d.id)throw new Error('email_request_failed');return d.id}
export function summary(d){return [['Reference',d.id],['Name',d.name],['Email',d.email],['Phone',d.phone],['Consultation',d.kind],['Preferred date',d.date],['Preferred time',d.time],['Timezone',d.timezone],['Event date',d.eventDate],['Guest count',d.guests],['Venue / city',d.location],['Budget range',d.budget],['Menu preferences',d.preferences],['Event details',d.details],['Client reminders requested',d.reminders?'Yes':'No']].map(([k,v])=>`${k}: ${v||'Not provided'}`).join('\n')}
export async function googleToken(){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:requiredEnv('GOOGLE_CLIENT_ID'),client_secret:requiredEnv('GOOGLE_CLIENT_SECRET'),refresh_token:requiredEnv('GOOGLE_REFRESH_TOKEN'),grant_type:'refresh_token'}),signal:AbortSignal.timeout(8000)});const d=await r.json();if(!r.ok||!d.access_token)throw new Error('calendar_auth_failed');return d.access_token}
export async function confirmCalendar(d,startISO){if(!capabilities().calendar)throw new Error('calendar_not_connected');const start=new Date(startISO),end=new Date(start.getTime()+20*60000);if(!Number.isFinite(start.getTime())||start.getTime()<Date.now()+30*60000||start.getTime()>Date.now()+365*86400000)throw new Error('Choose a future time within one year.');const token=await googleToken(),headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'},calendarId=requiredEnv('GOOGLE_CALENDAR_ID'),eventId=digest(d.id).slice(0,40),base=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`;
 // Deterministic event ID makes a retry safe after an uncertain calendar write.
 const existing=await fetch(`${base}/${eventId}`,{headers,signal:AbortSignal.timeout(8000)});if(existing.ok)return existing.json();
 if(existing.status!==404)throw new Error('calendar_lookup_failed');
 const fb=await fetch('https://www.googleapis.com/calendar/v3/freeBusy',{method:'POST',headers,body:JSON.stringify({timeMin:start.toISOString(),timeMax:end.toISOString(),items:[{id:calendarId}]}),signal:AbortSignal.timeout(8000)});const free=await fb.json();const c=free.calendars?.[calendarId];if(!fb.ok||!c||c.errors||c.busy.length)throw new Error('This time is busy or availability could not be checked.');
 const r=await fetch(`${base}?sendUpdates=all`,{method:'POST',headers,body:JSON.stringify({id:eventId,summary:`Sobre Mesa — ${d.kind} — ${d.name}`,description:`Consultation for Sobre Mesa. Reference ${d.id}.\nContact phone: ${d.phone||'Not provided'}\nEvent date: ${d.eventDate||'To discuss'}\nThis consultation does not confirm an event booking.`,start:{dateTime:start.toISOString()},end:{dateTime:end.toISOString()},attendees:[{email:d.email}],reminders:{useDefault:false,overrides:[{method:'popup',minutes:60},{method:'popup',minutes:1440}]},extendedProperties:{private:{sobreMesaRequest:d.id}}}),signal:AbortSignal.timeout(8000)});const e=await r.json();if(!r.ok){if(r.status===409){const retry=await fetch(`${base}/${eventId}`,{headers});if(retry.ok)return retry.json()}throw new Error('calendar_write_failed')}return e;
}
export async function scheduleReminders(d){if(!d.confirmedStart||!capabilities().email)return d;const start=new Date(d.confirmedStart).getTime();const name=d.kind,when=new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeStyle:'short',timeZone:d.timezone||'America/New_York'}).format(new Date(start));for(const [audience,to,enabled] of /** @type {Array<[string,string|undefined,boolean]>} */ ([['owner',process.env.CONCIERGE_OWNER_EMAIL,true],['client',d.email,d.reminders]])){ if(!enabled)continue;for(const [label,hours] of /** @type {Array<[string,number]>} */ ([['day',24],['hour',1]])){const k=`${audience}_${label}`,at=start-hours*3600000;if(d.notifications[k]||at<=Date.now()||at>Date.now()+29*86400000)continue;try{d.notifications[k]=await sendMail({to,subject:`Reminder: Sobre Mesa ${name}`,text:`Your ${name.toLowerCase()} with Sobre Mesa is scheduled for ${when} (${d.timezone||'America/New_York'}).\nReference: ${d.id}\nFor changes, contact chef@lasobremesa.vip or 804-866-7307.`,id:`${d.id}-${k}`,scheduled_at:new Date(at).toISOString()})}catch{d.notificationWarning=true}}}await redis(['SET',`sm:request:${d.id}`,JSON.stringify(d)]);return d}
